server:
  servlet:
    context-path: /web              # 请求前缀
    session:
      timeout: PT60M                  # session 过期时间，1小时
  port: 8192                          # 端口号

spring:
  mvc:
    # 未找到请求资源时不返回404，抛出 NoHandlerFoundException 异常
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false             # 关闭静态资源自动映射

  datasource:
    url: jdbc:mysql://localhost:3306/book?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  mail:
    host: smtp.qq.com                           # SMTP 服务器地址
    port: 465                                   # 邮件服务器端口 (465 或 587)
    default-encoding: UTF-8                     # 默认编码
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory   # 使用 SSL 连接
        debug: true                               # 开启调试模式，查看邮件发送的详细日志
    username: test@qq.com
    password: 123                                 # 使用邮箱官网申请的授权码

# mybatis 配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true                      # 开启驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 开启 SQL 日志

# 管理员账户和密码
admin:
  account: admin
  password: 123456

# 日志配置
log:
  root:
    level: debug                                 # 日志级别

# 项目路径配置
project:
  folder: D:/project_folder                   # 项目文件路径

# 开发环境标识
isDev: true